# Mule-Cloud 配置文件

# 服务器配置
server:
  name: "gateway"
  host: "0.0.0.0"
  port: 8080
  mode: "release"  # debug, release, test

# Consul配置
consul:
  enabled: true
  address: "127.0.0.1:8500"
  scheme: "http"
  # 服务注册
  service_id: ""  # 为空则自动生成
  service_name: "gateway"
  service_ip: "127.0.0.1"
  service_port: 8080
  tags:
    - "gateway"
    - "api"
  # 健康检查
  health_check_interval: "10s"
  health_check_timeout: "5s"
  deregister_after: "30s"

# JWT配置
jwt:
  secret_key: "mule-cloud-super-secret-key-change-in-production-min-32-chars"
  expire_time: 24  # 小时
  issuer: "mule-cloud"

# Hystrix熔断器配置
hystrix:
  enabled: true
  # 默认配置
  default:
    timeout: 3000  # 毫秒
    max_concurrent_requests: 100
    request_volume_threshold: 20
    sleep_window: 5000  # 毫秒
    error_percent_threshold: 50
  # 服务级别配置
  commands:
    testservice:
      timeout: 2000
      max_concurrent_requests: 50
      request_volume_threshold: 10
      sleep_window: 3000
      error_percent_threshold: 50
    basicservice:
      timeout: 5000
      max_concurrent_requests: 100
      request_volume_threshold: 20
      sleep_window: 5000
      error_percent_threshold: 60

# 网关配置
gateway:
  # 限流配置
  rate_limit:
    enabled: true
    rate: 100  # 每秒请求数
  # 超时配置
  timeout:
    read: 30   # 秒
    write: 30  # 秒
  # 路由配置
  routes:
    /test:
      service_name: "testservice"
      require_auth: true
      require_role: []
    /basic:
      service_name: "basicservice"
      require_auth: false
      require_role: []
    /admin:
      service_name: "testservice"
      require_auth: true
      require_role:
        - "admin"

# MongoDB配置
mongodb:
  enabled: false
  # 方式1: 使用URI连接（推荐）
  uri: "mongodb://localhost:27017"
  # 方式2: 使用独立配置
  host: "127.0.0.1"
  port: 27017
  username: ""
  password: ""
  database: "mule_cloud"
  auth_source: "admin"  # 认证数据库
  replica_set: ""       # 副本集名称（可选）
  max_pool_size: 100    # 最大连接池大小
  min_pool_size: 10     # 最小连接池大小
  timeout: 10           # 连接超时（秒）

# Redis配置（可选）
redis:
  enabled: false
  host: "127.0.0.1"
  port: 6379
  password: ""
  db: 0
  pool_size: 10

# 日志配置
log:
  level: "info"        # debug, info, warn, error
  format: "text"       # json, text
  output: "stdout"     # stdout, file
  file_path: "logs/app.log"
  max_size: 100        # MB
  max_backups: 3       # 保留旧文件数量
  max_age: 7           # 天
  compress: true       # 是否压缩
