services:
  # MongoDB数据库
  mongodb:
    image: mongo:6.0
    container_name: mule-cloud-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: mule_cloud
    volumes:
      - mongodb_data:/data/db
      - ./scripts/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - mule-cloud-network

  # Redis缓存
  redis:
    image: redis:7.0-alpine
    container_name: mule-cloud-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --requirepass "redis123"
    volumes:
      - redis_data:/data
    networks:
      - mule-cloud-network

  # Consul服务发现
  consul:
    image: consul:1.15
    container_name: mule-cloud-consul
    restart: unless-stopped
    ports:
      - "8500:8500"
      - "8600:8600/tcp"
      - "8600:8600/udp"
    command: consul agent -dev -client=0.0.0.0 -ui
    networks:
      - mule-cloud-network

# 网络配置
networks:
  mule-cloud-network:
    driver: bridge

# 数据卷
volumes:
  mongodb_data:
    driver: local
  redis_data:
    driver: local
