# Common Service 配置

server:
  name: "commonservice"
  host: "0.0.0.0"
  port: 8005
  mode: "debug"

consul:
  enabled: true
  address: "127.0.0.1:8500"
  scheme: "http"
  service_name: "commonservice"
  service_ip: "192.168.31.78"  # 使用实际的网卡 IP
  service_port: 8005
  tags:
    - "common"
    - "public"
  health_check_interval: "10s"
  health_check_timeout: "5s"
  deregister_after: "30s"

log:
  level: "info"
  format: "text"
  output: "stdout"

# MongoDB配置
mongodb:
  enabled: true
  host: "127.0.0.1"
  port: 27015
  username: "root"
  password: "bgg8384495"
  database: "mule"
  auth_source: "admin"
  replica_set: ""
  max_pool_size: 100
  min_pool_size: 10
  timeout: 10

# Redis配置（可选）
redis:
  enabled: false
  host: "127.0.0.1"
  port: 6379
  password: ""
  db: 0
  pool_size: 10

# JWT配置
jwt:
  secret: "your-secret-key-change-in-production"
  expire_hours: 24

# 文件存储配置
storage:
  type: "local"  # 存储类型: local/minio/s3/oss
  
  # 本地存储配置
  local:
    upload_dir: "./uploads"  # 上传目录
    base_url: "http://192.168.31.78:8005/files"  # 访问基础URL（与service_port一致）
  
  # MinIO配置（如果使用MinIO）
  minio:
    endpoint: "localhost:9000"
    access_key_id: "minioadmin"
    secret_access_key: "minioadmin"
    bucket_name: "mule-cloud"
    use_ssl: false
    region: "us-east-1"
  
  # S3配置（如果使用AWS S3）
  s3:
    endpoint: ""  # 留空使用AWS S3，填写则使用兼容S3的服务
    access_key_id: "your-access-key"
    secret_access_key: "your-secret-key"
    bucket_name: "mule-cloud"
    region: "us-east-1"
  
  # OSS配置（如果使用阿里云OSS）
  oss:
    endpoint: "oss-cn-hangzhou.aliyuncs.com"
    access_key_id: "your-access-key"
    access_key_secret: "your-secret-key"
    bucket_name: "mule-cloud"
