# Gateway 网关配置

server:
  name: "mule-cloud-gateway"
  host: "0.0.0.0"
  port: 8080
  mode: "debug"

consul:
  enabled: true
  address: "127.0.0.1:8500"
  scheme: "http"
  service_name: "gateway"
  service_ip: "localhost"
  service_port: 8080
  tags:
    - "gateway"
    - "api"
  health_check_interval: "10s"
  health_check_timeout: "5s"
  deregister_after: "30s"

jwt:
  secret_key: "mule-cloud-super-secret-key-change-in-production-min-32-chars"
  expire_time: 24
  issuer: "mule-cloud-gateway"

hystrix:
  enabled: true
  default:
    timeout: 3000
    max_concurrent_requests: 100
    request_volume_threshold: 20
    sleep_window: 5000
    error_percent_threshold: 50
  commands:
    authservice:
      timeout: 3000
      max_concurrent_requests: 100
      request_volume_threshold: 20
      sleep_window: 5000
      error_percent_threshold: 50
    testservice:
      timeout: 2000
      max_concurrent_requests: 50
      request_volume_threshold: 10
      sleep_window: 3000
      error_percent_threshold: 50
    basicservice:
      timeout: 5000
      max_concurrent_requests: 100
      request_volume_threshold: 20
      sleep_window: 5000
      error_percent_threshold: 60
    commonservice:
      timeout: 10000
      max_concurrent_requests: 100
      request_volume_threshold: 20
      sleep_window: 5000
      error_percent_threshold: 60

gateway:
  rate_limit:
    enabled: true
    rate: 100
  timeout:
    read: 30
    write: 30
  routes:
    /auth:
      service_name: "authservice"
      require_auth: false
      require_role: []
    /test:
      service_name: "testservice"
      require_auth: true
      require_role: []
    /basic:
      service_name: "basicservice"
      require_auth: false
      require_role: []
    /admin/common:
      service_name: "commonservice"
      require_auth: false
      require_role: []
    /admin:
      service_name: "testservice"
      require_auth: true
      require_role:
        - "admin"

log:
  level: "info"
  format: "text"
  output: "stdout"

# MongoDB配置
mongodb:
  enabled: true
  # 方式2: 使用独立配置
  host: "127.0.0.1"
  port: 27015
  username: "root"
  password: "bgg8384495"
  database: "mule"
  auth_source: "admin"  # 认证数据库
  replica_set: ""       # 副本集名称（可选）
  max_pool_size: 100    # 最大连接池大小
  min_pool_size: 10     # 最小连接池大小
  timeout: 10           # 连接超时（秒）