# Miniapp Service 配置

server:
  name: "miniappservice"
  host: "0.0.0.0"
  port: 8007
  mode: "debug"

consul:
  enabled: true
  address: "127.0.0.1:8500"
  scheme: "http"
  service_name: "miniappservice"
  service_ip: "192.168.31.78"  # 使用实际的网卡 IP，让 Consul 能访问
  service_port: 8007
  tags:
    - "miniapp"
    - "wechat"
    - "public"
  health_check_interval: "10s"
  health_check_timeout: "5s"
  deregister_after: "30s"

# JWT配置
jwt:
  secret_key: "mule-cloud-super-secret-key-change-in-production-min-32-chars"
  expire_time: 720  # 小程序token有效期30天（720小时）
  issuer: "mule-cloud-miniapp"

# 微信小程序配置
wechat:
  app_id: "wxef1a9745943156b6"        # 替换为实际的小程序AppID
  app_secret: "6e1198cc9d8b2d8546cc32efd32a7092"   # 替换为实际的小程序AppSecret
  # 如果有微信开放平台，配置UnionID
  # open_app_id: "your_open_platform_appid"

log:
  level: "info"
  format: "text"
  output: "stdout"

# MongoDB配置
mongodb:
  enabled: true
  host: "127.0.0.1"
  port: 27015
  username: "root"
  password: "bgg8384495"
  database: "mule"
  auth_source: "admin"  # 认证数据库
  replica_set: ""       # 副本集名称（可选）
  max_pool_size: 100    # 最大连接池大小
  min_pool_size: 10     # 最小连接池大小
  timeout: 10           # 连接超时（秒）

# Redis配置（可选）
redis:
  enabled: false
  host: "127.0.0.1"
  port: 6379
  password: "redis123"
  db: 0
  pool_size: 10

