# Perms Service 配置

server:
  name: "permservice"
  host: "0.0.0.0"
  port: 8003
  mode: "debug"

consul:
  enabled: true
  address: "127.0.0.1:8500"
  scheme: "http"
  service_name: "permservice"
  service_ip: "192.168.31.78"  # 使用实际的网卡 IP
  service_port: 8003
  tags:
    - "perms"
    - "admin"
    - "tenant"
  health_check_interval: "10s"
  health_check_timeout: "5s"
  deregister_after: "30s"

log:
  level: "info"
  format: "text"
  output: "stdout"

# MongoDB配置
mongodb:
  enabled: true
  # 方式2: 使用独立配置
  host: "127.0.0.1"
  port: 27015
  username: "root"
  password: "bgg8384495"
  database: "mule"
  auth_source: "admin"  # 认证数据库
  replica_set: ""       # 副本集名称（可选）
  max_pool_size: 100    # 最大连接池大小
  min_pool_size: 10     # 最小连接池大小
  timeout: 10           # 连接超时（秒）

# Redis配置（可选）
redis:
  enabled: false
  host: "127.0.0.1"
  port: 6379
  password: ""
  db: 0
  pool_size: 10

