# Mule Cloud 应用配置文件

# 应用基本配置
app:
  name: "mule-cloud"
  version: "1.0.0"
  environment: "development"  # development, production, testing
  debug: true

# 服务器配置
server:
  host: "0.0.0.0"
  port: 8080
  read_timeout: 10          # 秒
  write_timeout: 10         # 秒
  max_header_bytes: 1048576 # 1MB
  shutdown_timeout: 30      # 秒

# 数据库配置
database:
  driver: "mysql"           # mysql, postgres, sqlite
  host: "mysql.torm.site"
  port: 3306
  username: "mule-cloud"
  password: "QyrFj7FPwKQfWt4N"
  database: "mule-cloud"
  charset: "utf8mb4"
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_lifetime: 3600   # 秒

# 日志配置
log:
  level: "info"             # debug, info, warn, error, fatal, panic
  format: "text"            # text, json
  output: "stdout"          # stdout, stderr, file
  file_path: "./logs/app.log"
  max_size: 100             # MB
  max_backups: 3
  max_age: 7                # 天
  compress: true

# Redis配置 (可选)
redis:
  host: "localhost"
  port: 6379
  password: ""
  database: 0
  max_retries: 3
  pool_size: 10
  min_idle_conns: 5
